#!/bin/bash
current_time=$(date +"%Y-%m-%d %H:%M:%S")

echo -e "\n$current_time | \033[41;33m你正在进行部署环境清理操作,请谨慎选择\033[0m "

 
echo -e "\n$current_time | \033[1;33m1.仅清理依赖环境包(用于出错时重新安装依赖)\033[0m【不会清理已安装的机器人数据】"  
echo -e "$current_time | \033[1;31m2.清理所有数据+缓存,还原为全新下载未部署状态\033[0m【请务必重新建个数据库,并修改.env文件】"  

echo -e  "\n "
read -p "$current_time | 请选择输入: " yes;

if [ "$yes" == 1 ];then 
    rm -rf "vendor"
    echo -e "$current_time | \033[1;33m已清理依赖环境包,启动项目将自动安装依赖命令：./start.sh  \033[0m"  
elif [ "$yes" == 2 ];then 	
    rm -rf "vendor"
    rm -rf "runtime"
    echo -e "$current_time | \033[1;31m已清理所有数据+缓存(数据库未清理 - 如有必要建议新建一个数据库并修改.env后启动项目)\033[0m"  
    
else
    echo -e "$current_time | 已取消操作"
fi
exit;
	
	